### ISSUE TITLE
ECALL_SEND/RECV documentation not entirely clear

### ISSUE THREAD

**Issue by borancar** [hex-five/multizone-api#2]
The documentation specifies the message format as 4 ints, are these 32-bit ints or 64-bit ints on a 64-bit system? it would perhaps be better to specify in terms of bytes or 4xn-bit integers.

**Comment by cgarlati** [comment]
Message length is always 16 bytes regardless of the architecture (rv32/rv64).

To be updated in the upcoming v2.x.x

@borancar Thank you for pointing this out!
